apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # ❗️ 이전 실습에서 사용한 본인의 Docker Hub 이미지로 변경해주세요.
        image: your-dockerhub-username/todo-list-frontend:v1.0
        ports:
        - containerPort: 3000