apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
spec:
  type: ClusterIP # 클러스터 내부에서만 통신할 것이므로 ClusterIP
  selector:
    app: todo-db # app=todo-db 라는 라벨을 가진 Pod를 찾아 연결
  ports:
    - protocol: TCP
      port: 3306 # 서비스가 노출할 포트
      targetPort: 3306 # 서비스가 연결할 Pod의 포트
