apiVersion: v1
kind: Service
metadata:
  name: backend-server-service
spec:
  selector:
    app: backend-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # 30000~32767 사이 지정
  type: NodePort
